name: Build Container 

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Create credentials file
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > google_application_credentials.json

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Speaker Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/train/Dockerfile
          push: true
          tags: |
            linguerie-repository/${{ secrets.PROJECT_ID }}/training:latest
          cache-from: |
            type=registry,ref=linguerie-repository/${{ secrets.PROJECT_ID }}/training:buildcache
          cache-to: |
            type=registry,ref=linguerie-repository/${{ secrets.PROJECT_ID }}/training:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
